### ISSUE TITLE
Error running app.js

### ISSUE THREAD

**Issue by jiglesiasromero** [xurxodev/Catalog-API#1]
After doing npm install, I get this error running api rest:

```util.js:947
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function
    at Object.inherits (util.js:947:11)
    at Object.<anonymous> (/home/jiglesias/Projects/nodepoc/Product-Node-API/node_modules/spdy/lib/spdy/connection.js:86:6)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jiglesias/Projects/nodepoc/Product-Node-API/node_modules/spdy/lib/spdy.js:20:19)```

**Comment by jrgonzalez3** [comment]
server.use(restify.acceptParser(server.acceptable));
                   ^

TypeError: restify.acceptParser is not a function
    at Object.<anonymous> (/home/jr/Practicas/Catalog-API/app.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)


after npm install or node app.js
